insert into department (department_id, department_name) values (1, 'Computer Science');
insert into department (department_id, department_name) values (2, 'Mathematics');
insert into department (department_id, department_name) values (3, 'Chemistry');
insert into department (department_id, department_name) values (4, 'Physics');
insert into department (department_id, department_name) values (5, 'Biology');
insert into department (department_id, department_name) values (6, 'Communications');
insert into department (department_id, department_name) values (7, 'Marketing');
insert into department (department_id, department_name) values (8, 'Finance');
insert into department (department_id, department_name) values (9, 'Earth and Environmental Sciences');
insert into department (department_id, department_name) values (10, 'Political Science');
insert into department (department_id, department_name) values (11, 'English');
insert into department (department_id, department_name) values (12, 'Art');
insert into department (department_id, department_name) values (13, 'History');
insert into department (department_id, department_name) values (14, 'Psychology');
insert into department (department_id, department_name) values (15, 'Sociology');